# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Python image from the Python Docker Official Images repository
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Set environment variables
# Note: These should be set with real values or bound at runtime
ENV DEEPSEEK_API_KEY=your_deepseek_api_key
ENV GROK_API_KEY=your_grok_api_key
ENV GOOGLE_API_KEY=your_google_api_key
ENV ANTHROPIC_API_KEY=your_anthropic_api_key
ENV OPENAI_API_KEY=your_openai_api_key

# Run app.py when the container launches
CMD ["python", "app.py"]
